---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "ubuntu"


  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "ubuntu"


  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "ubuntu"



  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "Amazon"


  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "Amazon"


  - name: add php support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "Amazon"
